name: readoutto-me
services:
  web:
    build: .
    volumes:
      - data:/app/data
    environment:
      - PORT=8023
    ports:
      - '127.0.0.1:8023:8023'
    restart: unless-stopped

volumes:
  data:
